/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ng2-pg-table[_ngcontent-%COMP%] {\n  display: inline-block;\n  float: left;\n  width: auto;\n  padding: 5px;\n  border-collapse: collapse !important;\n}\n\ntable-pagination[_ngcontent-%COMP%] {\n  margin: auto;\n  text-align: center;\n  display: block;\n  cursor: default;\n}\n\n.pagination[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n  cursor: pointer !important;\n}\n\n.glyphicon[_ngcontent-%COMP%] {\n  top: 0 !important;\n}\n\n.ng2-pg-table[_ngcontent-%COMP%]   tr[_ngcontent-%COMP%]   td[_ngcontent-%COMP%], .ng2-pg-table[_ngcontent-%COMP%]   tr[_ngcontent-%COMP%]   th[_ngcontent-%COMP%] {\n  cursor: pointer;\n}\n\n.table-floating-menu[_ngcontent-%COMP%] {\n  position: fixed;\n  z-index: 99999;\n  cursor: pointer !important;\n}\n\n.filter-clear-button[_ngcontent-%COMP%] {\n  padding: 0 4px !important;\n}\n\n.hovered[_ngcontent-%COMP%] {\n  background-color: #f5f5f5;\n}\n\n.selected[_ngcontent-%COMP%] {\n  background-color: #a9a9a9 !important;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci9wcm9qZWN0cy9nZW5lcmF0b3IyL3NyYy90YWJsZS5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy92YXIvcHJvamVjdHMvZ2VuZXJhdG9yMi9zcmMvdGFibGUuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
